# 백엔드 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planit-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planit-backend
  template:
    metadata:
      labels:
        app: planit-backend
    spec:
      containers:
        - name: app
          image: 713881824287.dkr.ecr.ap-northeast-2.amazonaws.com/planit-was:prod
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: planit-backend-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: TZ
              value: "Asia/Seoul"
            - name: AWS_REGION
              value: "ap-northeast-2"
