# 백엔드 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planit-backend
  namespace: planit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planit-backend
  template:
    metadata:
      labels:
        app: planit-backend
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: planit-backend
      containers:
        - name: app
          image: 713881824287.dkr.ecr.ap-northeast-2.amazonaws.com/planit-was:prod
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 5
            failureThreshold: 2
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 5
          envFrom:
            - secretRef:
                name: planit-backend-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: TZ
              value: "Asia/Seoul"
            - name: AWS_REGION
              value: "ap-northeast-2"
          resources:
            requests:
              cpu: "400m"
              memory: "512Mi"
            limits:
              cpu: "600m"
              memory: "1024Mi"
