apiVersion: v1
kind: Secret
metadata:
  name: planit-backend-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: ""
  SPRING_DATASOURCE_PASSWORD: ""
  SPRING_DATASOURCE_URL: ""
  GOOGLE_MAPS_API_KEY: ""
  SPRING_DATA_REDIS_HOST: ""
  SPRING_DATA_REDIS_PORT: ""
  SPRING_DATA_REDIS_PASSWORD: ""
  SPRING_DATA_MONGODB_URI: ""
  AI_BASE_URL: ""
  JWT_SECRET: ""
  AWS_S3_BUCKET: ""
  CLOUDFRONT_DOMAIN: ""