# 백엔드 Service
apiVersion: v1
kind: Service
metadata:
  name: planit-backend-service
  namespace: planit-app
spec:
  selector:
    app: planit-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP