apiVersion: v1
kind: Service
metadata:
  name: planit-chat-service
  namespace: planit-app
spec:
  selector:
    app: planit-chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP